# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hopson/projects/cpp/Hopson-Arcade

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hopson/projects/cpp/Hopson-Arcade

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hopson/projects/cpp/Hopson-Arcade/CMakeFiles /home/hopson/projects/cpp/Hopson-Arcade/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hopson/projects/cpp/Hopson-Arcade/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HopsonArcade

# Build rule for target.
HopsonArcade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HopsonArcade
.PHONY : HopsonArcade

# fast build rule for target.
HopsonArcade/fast:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/build
.PHONY : HopsonArcade/fast

Source/Arcade/Game.o: Source/Arcade/Game.cpp.o

.PHONY : Source/Arcade/Game.o

# target to build an object file
Source/Arcade/Game.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Arcade/Game.cpp.o
.PHONY : Source/Arcade/Game.cpp.o

Source/Arcade/Game.i: Source/Arcade/Game.cpp.i

.PHONY : Source/Arcade/Game.i

# target to preprocess a source file
Source/Arcade/Game.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Arcade/Game.cpp.i
.PHONY : Source/Arcade/Game.cpp.i

Source/Arcade/Game.s: Source/Arcade/Game.cpp.s

.PHONY : Source/Arcade/Game.s

# target to generate assembly for a file
Source/Arcade/Game.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Arcade/Game.cpp.s
.PHONY : Source/Arcade/Game.cpp.s

Source/Arcade/Main.o: Source/Arcade/Main.cpp.o

.PHONY : Source/Arcade/Main.o

# target to build an object file
Source/Arcade/Main.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Arcade/Main.cpp.o
.PHONY : Source/Arcade/Main.cpp.o

Source/Arcade/Main.i: Source/Arcade/Main.cpp.i

.PHONY : Source/Arcade/Main.i

# target to preprocess a source file
Source/Arcade/Main.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Arcade/Main.cpp.i
.PHONY : Source/Arcade/Main.cpp.i

Source/Arcade/Main.s: Source/Arcade/Main.cpp.s

.PHONY : Source/Arcade/Main.s

# target to generate assembly for a file
Source/Arcade/Main.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Arcade/Main.cpp.s
.PHONY : Source/Arcade/Main.cpp.s

Source/Framework/GUI/Button.o: Source/Framework/GUI/Button.cpp.o

.PHONY : Source/Framework/GUI/Button.o

# target to build an object file
Source/Framework/GUI/Button.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Button.cpp.o
.PHONY : Source/Framework/GUI/Button.cpp.o

Source/Framework/GUI/Button.i: Source/Framework/GUI/Button.cpp.i

.PHONY : Source/Framework/GUI/Button.i

# target to preprocess a source file
Source/Framework/GUI/Button.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Button.cpp.i
.PHONY : Source/Framework/GUI/Button.cpp.i

Source/Framework/GUI/Button.s: Source/Framework/GUI/Button.cpp.s

.PHONY : Source/Framework/GUI/Button.s

# target to generate assembly for a file
Source/Framework/GUI/Button.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Button.cpp.s
.PHONY : Source/Framework/GUI/Button.cpp.s

Source/Framework/GUI/StackMenu.o: Source/Framework/GUI/StackMenu.cpp.o

.PHONY : Source/Framework/GUI/StackMenu.o

# target to build an object file
Source/Framework/GUI/StackMenu.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/StackMenu.cpp.o
.PHONY : Source/Framework/GUI/StackMenu.cpp.o

Source/Framework/GUI/StackMenu.i: Source/Framework/GUI/StackMenu.cpp.i

.PHONY : Source/Framework/GUI/StackMenu.i

# target to preprocess a source file
Source/Framework/GUI/StackMenu.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/StackMenu.cpp.i
.PHONY : Source/Framework/GUI/StackMenu.cpp.i

Source/Framework/GUI/StackMenu.s: Source/Framework/GUI/StackMenu.cpp.s

.PHONY : Source/Framework/GUI/StackMenu.s

# target to generate assembly for a file
Source/Framework/GUI/StackMenu.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/StackMenu.cpp.s
.PHONY : Source/Framework/GUI/StackMenu.cpp.s

Source/Framework/GUI/Textbox.o: Source/Framework/GUI/Textbox.cpp.o

.PHONY : Source/Framework/GUI/Textbox.o

# target to build an object file
Source/Framework/GUI/Textbox.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Textbox.cpp.o
.PHONY : Source/Framework/GUI/Textbox.cpp.o

Source/Framework/GUI/Textbox.i: Source/Framework/GUI/Textbox.cpp.i

.PHONY : Source/Framework/GUI/Textbox.i

# target to preprocess a source file
Source/Framework/GUI/Textbox.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Textbox.cpp.i
.PHONY : Source/Framework/GUI/Textbox.cpp.i

Source/Framework/GUI/Textbox.s: Source/Framework/GUI/Textbox.cpp.s

.PHONY : Source/Framework/GUI/Textbox.s

# target to generate assembly for a file
Source/Framework/GUI/Textbox.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Textbox.cpp.s
.PHONY : Source/Framework/GUI/Textbox.cpp.s

Source/Framework/GUI/Widget.o: Source/Framework/GUI/Widget.cpp.o

.PHONY : Source/Framework/GUI/Widget.o

# target to build an object file
Source/Framework/GUI/Widget.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Widget.cpp.o
.PHONY : Source/Framework/GUI/Widget.cpp.o

Source/Framework/GUI/Widget.i: Source/Framework/GUI/Widget.cpp.i

.PHONY : Source/Framework/GUI/Widget.i

# target to preprocess a source file
Source/Framework/GUI/Widget.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Widget.cpp.i
.PHONY : Source/Framework/GUI/Widget.cpp.i

Source/Framework/GUI/Widget.s: Source/Framework/GUI/Widget.cpp.s

.PHONY : Source/Framework/GUI/Widget.s

# target to generate assembly for a file
Source/Framework/GUI/Widget.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/GUI/Widget.cpp.s
.PHONY : Source/Framework/GUI/Widget.cpp.s

Source/Framework/ResourceManager/ResourceHolder.o: Source/Framework/ResourceManager/ResourceHolder.cpp.o

.PHONY : Source/Framework/ResourceManager/ResourceHolder.o

# target to build an object file
Source/Framework/ResourceManager/ResourceHolder.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/ResourceManager/ResourceHolder.cpp.o
.PHONY : Source/Framework/ResourceManager/ResourceHolder.cpp.o

Source/Framework/ResourceManager/ResourceHolder.i: Source/Framework/ResourceManager/ResourceHolder.cpp.i

.PHONY : Source/Framework/ResourceManager/ResourceHolder.i

# target to preprocess a source file
Source/Framework/ResourceManager/ResourceHolder.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/ResourceManager/ResourceHolder.cpp.i
.PHONY : Source/Framework/ResourceManager/ResourceHolder.cpp.i

Source/Framework/ResourceManager/ResourceHolder.s: Source/Framework/ResourceManager/ResourceHolder.cpp.s

.PHONY : Source/Framework/ResourceManager/ResourceHolder.s

# target to generate assembly for a file
Source/Framework/ResourceManager/ResourceHolder.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/ResourceManager/ResourceHolder.cpp.s
.PHONY : Source/Framework/ResourceManager/ResourceHolder.cpp.s

Source/Framework/Util/Animation.o: Source/Framework/Util/Animation.cpp.o

.PHONY : Source/Framework/Util/Animation.o

# target to build an object file
Source/Framework/Util/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/Animation.cpp.o
.PHONY : Source/Framework/Util/Animation.cpp.o

Source/Framework/Util/Animation.i: Source/Framework/Util/Animation.cpp.i

.PHONY : Source/Framework/Util/Animation.i

# target to preprocess a source file
Source/Framework/Util/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/Animation.cpp.i
.PHONY : Source/Framework/Util/Animation.cpp.i

Source/Framework/Util/Animation.s: Source/Framework/Util/Animation.cpp.s

.PHONY : Source/Framework/Util/Animation.s

# target to generate assembly for a file
Source/Framework/Util/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/Animation.cpp.s
.PHONY : Source/Framework/Util/Animation.cpp.s

Source/Framework/Util/FPSCounter.o: Source/Framework/Util/FPSCounter.cpp.o

.PHONY : Source/Framework/Util/FPSCounter.o

# target to build an object file
Source/Framework/Util/FPSCounter.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/FPSCounter.cpp.o
.PHONY : Source/Framework/Util/FPSCounter.cpp.o

Source/Framework/Util/FPSCounter.i: Source/Framework/Util/FPSCounter.cpp.i

.PHONY : Source/Framework/Util/FPSCounter.i

# target to preprocess a source file
Source/Framework/Util/FPSCounter.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/FPSCounter.cpp.i
.PHONY : Source/Framework/Util/FPSCounter.cpp.i

Source/Framework/Util/FPSCounter.s: Source/Framework/Util/FPSCounter.cpp.s

.PHONY : Source/Framework/Util/FPSCounter.s

# target to generate assembly for a file
Source/Framework/Util/FPSCounter.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/FPSCounter.cpp.s
.PHONY : Source/Framework/Util/FPSCounter.cpp.s

Source/Framework/Util/FileUtil.o: Source/Framework/Util/FileUtil.cpp.o

.PHONY : Source/Framework/Util/FileUtil.o

# target to build an object file
Source/Framework/Util/FileUtil.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/FileUtil.cpp.o
.PHONY : Source/Framework/Util/FileUtil.cpp.o

Source/Framework/Util/FileUtil.i: Source/Framework/Util/FileUtil.cpp.i

.PHONY : Source/Framework/Util/FileUtil.i

# target to preprocess a source file
Source/Framework/Util/FileUtil.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/FileUtil.cpp.i
.PHONY : Source/Framework/Util/FileUtil.cpp.i

Source/Framework/Util/FileUtil.s: Source/Framework/Util/FileUtil.cpp.s

.PHONY : Source/Framework/Util/FileUtil.s

# target to generate assembly for a file
Source/Framework/Util/FileUtil.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/FileUtil.cpp.s
.PHONY : Source/Framework/Util/FileUtil.cpp.s

Source/Framework/Util/Maths.o: Source/Framework/Util/Maths.cpp.o

.PHONY : Source/Framework/Util/Maths.o

# target to build an object file
Source/Framework/Util/Maths.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/Maths.cpp.o
.PHONY : Source/Framework/Util/Maths.cpp.o

Source/Framework/Util/Maths.i: Source/Framework/Util/Maths.cpp.i

.PHONY : Source/Framework/Util/Maths.i

# target to preprocess a source file
Source/Framework/Util/Maths.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/Maths.cpp.i
.PHONY : Source/Framework/Util/Maths.cpp.i

Source/Framework/Util/Maths.s: Source/Framework/Util/Maths.cpp.s

.PHONY : Source/Framework/Util/Maths.s

# target to generate assembly for a file
Source/Framework/Util/Maths.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/Maths.cpp.s
.PHONY : Source/Framework/Util/Maths.cpp.s

Source/Framework/Util/ToggleKey.o: Source/Framework/Util/ToggleKey.cpp.o

.PHONY : Source/Framework/Util/ToggleKey.o

# target to build an object file
Source/Framework/Util/ToggleKey.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/ToggleKey.cpp.o
.PHONY : Source/Framework/Util/ToggleKey.cpp.o

Source/Framework/Util/ToggleKey.i: Source/Framework/Util/ToggleKey.cpp.i

.PHONY : Source/Framework/Util/ToggleKey.i

# target to preprocess a source file
Source/Framework/Util/ToggleKey.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/ToggleKey.cpp.i
.PHONY : Source/Framework/Util/ToggleKey.cpp.i

Source/Framework/Util/ToggleKey.s: Source/Framework/Util/ToggleKey.cpp.s

.PHONY : Source/Framework/Util/ToggleKey.s

# target to generate assembly for a file
Source/Framework/Util/ToggleKey.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/Framework/Util/ToggleKey.cpp.s
.PHONY : Source/Framework/Util/ToggleKey.cpp.s

Source/SpaceInvaders/AnimationRenderer.o: Source/SpaceInvaders/AnimationRenderer.cpp.o

.PHONY : Source/SpaceInvaders/AnimationRenderer.o

# target to build an object file
Source/SpaceInvaders/AnimationRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/AnimationRenderer.cpp.o
.PHONY : Source/SpaceInvaders/AnimationRenderer.cpp.o

Source/SpaceInvaders/AnimationRenderer.i: Source/SpaceInvaders/AnimationRenderer.cpp.i

.PHONY : Source/SpaceInvaders/AnimationRenderer.i

# target to preprocess a source file
Source/SpaceInvaders/AnimationRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/AnimationRenderer.cpp.i
.PHONY : Source/SpaceInvaders/AnimationRenderer.cpp.i

Source/SpaceInvaders/AnimationRenderer.s: Source/SpaceInvaders/AnimationRenderer.cpp.s

.PHONY : Source/SpaceInvaders/AnimationRenderer.s

# target to generate assembly for a file
Source/SpaceInvaders/AnimationRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/AnimationRenderer.cpp.s
.PHONY : Source/SpaceInvaders/AnimationRenderer.cpp.s

Source/SpaceInvaders/Collidable.o: Source/SpaceInvaders/Collidable.cpp.o

.PHONY : Source/SpaceInvaders/Collidable.o

# target to build an object file
Source/SpaceInvaders/Collidable.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Collidable.cpp.o
.PHONY : Source/SpaceInvaders/Collidable.cpp.o

Source/SpaceInvaders/Collidable.i: Source/SpaceInvaders/Collidable.cpp.i

.PHONY : Source/SpaceInvaders/Collidable.i

# target to preprocess a source file
Source/SpaceInvaders/Collidable.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Collidable.cpp.i
.PHONY : Source/SpaceInvaders/Collidable.cpp.i

Source/SpaceInvaders/Collidable.s: Source/SpaceInvaders/Collidable.cpp.s

.PHONY : Source/SpaceInvaders/Collidable.s

# target to generate assembly for a file
Source/SpaceInvaders/Collidable.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Collidable.cpp.s
.PHONY : Source/SpaceInvaders/Collidable.cpp.s

Source/SpaceInvaders/Entity/Explosion.o: Source/SpaceInvaders/Entity/Explosion.cpp.o

.PHONY : Source/SpaceInvaders/Entity/Explosion.o

# target to build an object file
Source/SpaceInvaders/Entity/Explosion.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Explosion.cpp.o
.PHONY : Source/SpaceInvaders/Entity/Explosion.cpp.o

Source/SpaceInvaders/Entity/Explosion.i: Source/SpaceInvaders/Entity/Explosion.cpp.i

.PHONY : Source/SpaceInvaders/Entity/Explosion.i

# target to preprocess a source file
Source/SpaceInvaders/Entity/Explosion.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Explosion.cpp.i
.PHONY : Source/SpaceInvaders/Entity/Explosion.cpp.i

Source/SpaceInvaders/Entity/Explosion.s: Source/SpaceInvaders/Entity/Explosion.cpp.s

.PHONY : Source/SpaceInvaders/Entity/Explosion.s

# target to generate assembly for a file
Source/SpaceInvaders/Entity/Explosion.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Explosion.cpp.s
.PHONY : Source/SpaceInvaders/Entity/Explosion.cpp.s

Source/SpaceInvaders/Entity/Invader.o: Source/SpaceInvaders/Entity/Invader.cpp.o

.PHONY : Source/SpaceInvaders/Entity/Invader.o

# target to build an object file
Source/SpaceInvaders/Entity/Invader.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Invader.cpp.o
.PHONY : Source/SpaceInvaders/Entity/Invader.cpp.o

Source/SpaceInvaders/Entity/Invader.i: Source/SpaceInvaders/Entity/Invader.cpp.i

.PHONY : Source/SpaceInvaders/Entity/Invader.i

# target to preprocess a source file
Source/SpaceInvaders/Entity/Invader.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Invader.cpp.i
.PHONY : Source/SpaceInvaders/Entity/Invader.cpp.i

Source/SpaceInvaders/Entity/Invader.s: Source/SpaceInvaders/Entity/Invader.cpp.s

.PHONY : Source/SpaceInvaders/Entity/Invader.s

# target to generate assembly for a file
Source/SpaceInvaders/Entity/Invader.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Invader.cpp.s
.PHONY : Source/SpaceInvaders/Entity/Invader.cpp.s

Source/SpaceInvaders/Entity/Player.o: Source/SpaceInvaders/Entity/Player.cpp.o

.PHONY : Source/SpaceInvaders/Entity/Player.o

# target to build an object file
Source/SpaceInvaders/Entity/Player.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Player.cpp.o
.PHONY : Source/SpaceInvaders/Entity/Player.cpp.o

Source/SpaceInvaders/Entity/Player.i: Source/SpaceInvaders/Entity/Player.cpp.i

.PHONY : Source/SpaceInvaders/Entity/Player.i

# target to preprocess a source file
Source/SpaceInvaders/Entity/Player.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Player.cpp.i
.PHONY : Source/SpaceInvaders/Entity/Player.cpp.i

Source/SpaceInvaders/Entity/Player.s: Source/SpaceInvaders/Entity/Player.cpp.s

.PHONY : Source/SpaceInvaders/Entity/Player.s

# target to generate assembly for a file
Source/SpaceInvaders/Entity/Player.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Player.cpp.s
.PHONY : Source/SpaceInvaders/Entity/Player.cpp.s

Source/SpaceInvaders/Entity/Projectile.o: Source/SpaceInvaders/Entity/Projectile.cpp.o

.PHONY : Source/SpaceInvaders/Entity/Projectile.o

# target to build an object file
Source/SpaceInvaders/Entity/Projectile.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Projectile.cpp.o
.PHONY : Source/SpaceInvaders/Entity/Projectile.cpp.o

Source/SpaceInvaders/Entity/Projectile.i: Source/SpaceInvaders/Entity/Projectile.cpp.i

.PHONY : Source/SpaceInvaders/Entity/Projectile.i

# target to preprocess a source file
Source/SpaceInvaders/Entity/Projectile.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Projectile.cpp.i
.PHONY : Source/SpaceInvaders/Entity/Projectile.cpp.i

Source/SpaceInvaders/Entity/Projectile.s: Source/SpaceInvaders/Entity/Projectile.cpp.s

.PHONY : Source/SpaceInvaders/Entity/Projectile.s

# target to generate assembly for a file
Source/SpaceInvaders/Entity/Projectile.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Projectile.cpp.s
.PHONY : Source/SpaceInvaders/Entity/Projectile.cpp.s

Source/SpaceInvaders/Entity/Shield.o: Source/SpaceInvaders/Entity/Shield.cpp.o

.PHONY : Source/SpaceInvaders/Entity/Shield.o

# target to build an object file
Source/SpaceInvaders/Entity/Shield.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Shield.cpp.o
.PHONY : Source/SpaceInvaders/Entity/Shield.cpp.o

Source/SpaceInvaders/Entity/Shield.i: Source/SpaceInvaders/Entity/Shield.cpp.i

.PHONY : Source/SpaceInvaders/Entity/Shield.i

# target to preprocess a source file
Source/SpaceInvaders/Entity/Shield.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Shield.cpp.i
.PHONY : Source/SpaceInvaders/Entity/Shield.cpp.i

Source/SpaceInvaders/Entity/Shield.s: Source/SpaceInvaders/Entity/Shield.cpp.s

.PHONY : Source/SpaceInvaders/Entity/Shield.s

# target to generate assembly for a file
Source/SpaceInvaders/Entity/Shield.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/Shield.cpp.s
.PHONY : Source/SpaceInvaders/Entity/Shield.cpp.s

Source/SpaceInvaders/Entity/UFO.o: Source/SpaceInvaders/Entity/UFO.cpp.o

.PHONY : Source/SpaceInvaders/Entity/UFO.o

# target to build an object file
Source/SpaceInvaders/Entity/UFO.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/UFO.cpp.o
.PHONY : Source/SpaceInvaders/Entity/UFO.cpp.o

Source/SpaceInvaders/Entity/UFO.i: Source/SpaceInvaders/Entity/UFO.cpp.i

.PHONY : Source/SpaceInvaders/Entity/UFO.i

# target to preprocess a source file
Source/SpaceInvaders/Entity/UFO.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/UFO.cpp.i
.PHONY : Source/SpaceInvaders/Entity/UFO.cpp.i

Source/SpaceInvaders/Entity/UFO.s: Source/SpaceInvaders/Entity/UFO.cpp.s

.PHONY : Source/SpaceInvaders/Entity/UFO.s

# target to generate assembly for a file
Source/SpaceInvaders/Entity/UFO.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/Entity/UFO.cpp.s
.PHONY : Source/SpaceInvaders/Entity/UFO.cpp.s

Source/SpaceInvaders/InvaderManager.o: Source/SpaceInvaders/InvaderManager.cpp.o

.PHONY : Source/SpaceInvaders/InvaderManager.o

# target to build an object file
Source/SpaceInvaders/InvaderManager.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/InvaderManager.cpp.o
.PHONY : Source/SpaceInvaders/InvaderManager.cpp.o

Source/SpaceInvaders/InvaderManager.i: Source/SpaceInvaders/InvaderManager.cpp.i

.PHONY : Source/SpaceInvaders/InvaderManager.i

# target to preprocess a source file
Source/SpaceInvaders/InvaderManager.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/InvaderManager.cpp.i
.PHONY : Source/SpaceInvaders/InvaderManager.cpp.i

Source/SpaceInvaders/InvaderManager.s: Source/SpaceInvaders/InvaderManager.cpp.s

.PHONY : Source/SpaceInvaders/InvaderManager.s

# target to generate assembly for a file
Source/SpaceInvaders/InvaderManager.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/InvaderManager.cpp.s
.PHONY : Source/SpaceInvaders/InvaderManager.cpp.s

Source/SpaceInvaders/StarryBackground.o: Source/SpaceInvaders/StarryBackground.cpp.o

.PHONY : Source/SpaceInvaders/StarryBackground.o

# target to build an object file
Source/SpaceInvaders/StarryBackground.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/StarryBackground.cpp.o
.PHONY : Source/SpaceInvaders/StarryBackground.cpp.o

Source/SpaceInvaders/StarryBackground.i: Source/SpaceInvaders/StarryBackground.cpp.i

.PHONY : Source/SpaceInvaders/StarryBackground.i

# target to preprocess a source file
Source/SpaceInvaders/StarryBackground.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/StarryBackground.cpp.i
.PHONY : Source/SpaceInvaders/StarryBackground.cpp.i

Source/SpaceInvaders/StarryBackground.s: Source/SpaceInvaders/StarryBackground.cpp.s

.PHONY : Source/SpaceInvaders/StarryBackground.s

# target to generate assembly for a file
Source/SpaceInvaders/StarryBackground.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/StarryBackground.cpp.s
.PHONY : Source/SpaceInvaders/StarryBackground.cpp.s

Source/SpaceInvaders/States/StateHighscores.o: Source/SpaceInvaders/States/StateHighscores.cpp.o

.PHONY : Source/SpaceInvaders/States/StateHighscores.o

# target to build an object file
Source/SpaceInvaders/States/StateHighscores.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StateHighscores.cpp.o
.PHONY : Source/SpaceInvaders/States/StateHighscores.cpp.o

Source/SpaceInvaders/States/StateHighscores.i: Source/SpaceInvaders/States/StateHighscores.cpp.i

.PHONY : Source/SpaceInvaders/States/StateHighscores.i

# target to preprocess a source file
Source/SpaceInvaders/States/StateHighscores.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StateHighscores.cpp.i
.PHONY : Source/SpaceInvaders/States/StateHighscores.cpp.i

Source/SpaceInvaders/States/StateHighscores.s: Source/SpaceInvaders/States/StateHighscores.cpp.s

.PHONY : Source/SpaceInvaders/States/StateHighscores.s

# target to generate assembly for a file
Source/SpaceInvaders/States/StateHighscores.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StateHighscores.cpp.s
.PHONY : Source/SpaceInvaders/States/StateHighscores.cpp.s

Source/SpaceInvaders/States/StateMainMenu.o: Source/SpaceInvaders/States/StateMainMenu.cpp.o

.PHONY : Source/SpaceInvaders/States/StateMainMenu.o

# target to build an object file
Source/SpaceInvaders/States/StateMainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StateMainMenu.cpp.o
.PHONY : Source/SpaceInvaders/States/StateMainMenu.cpp.o

Source/SpaceInvaders/States/StateMainMenu.i: Source/SpaceInvaders/States/StateMainMenu.cpp.i

.PHONY : Source/SpaceInvaders/States/StateMainMenu.i

# target to preprocess a source file
Source/SpaceInvaders/States/StateMainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StateMainMenu.cpp.i
.PHONY : Source/SpaceInvaders/States/StateMainMenu.cpp.i

Source/SpaceInvaders/States/StateMainMenu.s: Source/SpaceInvaders/States/StateMainMenu.cpp.s

.PHONY : Source/SpaceInvaders/States/StateMainMenu.s

# target to generate assembly for a file
Source/SpaceInvaders/States/StateMainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StateMainMenu.cpp.s
.PHONY : Source/SpaceInvaders/States/StateMainMenu.cpp.s

Source/SpaceInvaders/States/StatePlaying.o: Source/SpaceInvaders/States/StatePlaying.cpp.o

.PHONY : Source/SpaceInvaders/States/StatePlaying.o

# target to build an object file
Source/SpaceInvaders/States/StatePlaying.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StatePlaying.cpp.o
.PHONY : Source/SpaceInvaders/States/StatePlaying.cpp.o

Source/SpaceInvaders/States/StatePlaying.i: Source/SpaceInvaders/States/StatePlaying.cpp.i

.PHONY : Source/SpaceInvaders/States/StatePlaying.i

# target to preprocess a source file
Source/SpaceInvaders/States/StatePlaying.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StatePlaying.cpp.i
.PHONY : Source/SpaceInvaders/States/StatePlaying.cpp.i

Source/SpaceInvaders/States/StatePlaying.s: Source/SpaceInvaders/States/StatePlaying.cpp.s

.PHONY : Source/SpaceInvaders/States/StatePlaying.s

# target to generate assembly for a file
Source/SpaceInvaders/States/StatePlaying.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/States/StatePlaying.cpp.s
.PHONY : Source/SpaceInvaders/States/StatePlaying.cpp.s

Source/SpaceInvaders/World.o: Source/SpaceInvaders/World.cpp.o

.PHONY : Source/SpaceInvaders/World.o

# target to build an object file
Source/SpaceInvaders/World.cpp.o:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/World.cpp.o
.PHONY : Source/SpaceInvaders/World.cpp.o

Source/SpaceInvaders/World.i: Source/SpaceInvaders/World.cpp.i

.PHONY : Source/SpaceInvaders/World.i

# target to preprocess a source file
Source/SpaceInvaders/World.cpp.i:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/World.cpp.i
.PHONY : Source/SpaceInvaders/World.cpp.i

Source/SpaceInvaders/World.s: Source/SpaceInvaders/World.cpp.s

.PHONY : Source/SpaceInvaders/World.s

# target to generate assembly for a file
Source/SpaceInvaders/World.cpp.s:
	$(MAKE) -f CMakeFiles/HopsonArcade.dir/build.make CMakeFiles/HopsonArcade.dir/Source/SpaceInvaders/World.cpp.s
.PHONY : Source/SpaceInvaders/World.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HopsonArcade"
	@echo "... Source/Arcade/Game.o"
	@echo "... Source/Arcade/Game.i"
	@echo "... Source/Arcade/Game.s"
	@echo "... Source/Arcade/Main.o"
	@echo "... Source/Arcade/Main.i"
	@echo "... Source/Arcade/Main.s"
	@echo "... Source/Framework/GUI/Button.o"
	@echo "... Source/Framework/GUI/Button.i"
	@echo "... Source/Framework/GUI/Button.s"
	@echo "... Source/Framework/GUI/StackMenu.o"
	@echo "... Source/Framework/GUI/StackMenu.i"
	@echo "... Source/Framework/GUI/StackMenu.s"
	@echo "... Source/Framework/GUI/Textbox.o"
	@echo "... Source/Framework/GUI/Textbox.i"
	@echo "... Source/Framework/GUI/Textbox.s"
	@echo "... Source/Framework/GUI/Widget.o"
	@echo "... Source/Framework/GUI/Widget.i"
	@echo "... Source/Framework/GUI/Widget.s"
	@echo "... Source/Framework/ResourceManager/ResourceHolder.o"
	@echo "... Source/Framework/ResourceManager/ResourceHolder.i"
	@echo "... Source/Framework/ResourceManager/ResourceHolder.s"
	@echo "... Source/Framework/Util/Animation.o"
	@echo "... Source/Framework/Util/Animation.i"
	@echo "... Source/Framework/Util/Animation.s"
	@echo "... Source/Framework/Util/FPSCounter.o"
	@echo "... Source/Framework/Util/FPSCounter.i"
	@echo "... Source/Framework/Util/FPSCounter.s"
	@echo "... Source/Framework/Util/FileUtil.o"
	@echo "... Source/Framework/Util/FileUtil.i"
	@echo "... Source/Framework/Util/FileUtil.s"
	@echo "... Source/Framework/Util/Maths.o"
	@echo "... Source/Framework/Util/Maths.i"
	@echo "... Source/Framework/Util/Maths.s"
	@echo "... Source/Framework/Util/ToggleKey.o"
	@echo "... Source/Framework/Util/ToggleKey.i"
	@echo "... Source/Framework/Util/ToggleKey.s"
	@echo "... Source/SpaceInvaders/AnimationRenderer.o"
	@echo "... Source/SpaceInvaders/AnimationRenderer.i"
	@echo "... Source/SpaceInvaders/AnimationRenderer.s"
	@echo "... Source/SpaceInvaders/Collidable.o"
	@echo "... Source/SpaceInvaders/Collidable.i"
	@echo "... Source/SpaceInvaders/Collidable.s"
	@echo "... Source/SpaceInvaders/Entity/Explosion.o"
	@echo "... Source/SpaceInvaders/Entity/Explosion.i"
	@echo "... Source/SpaceInvaders/Entity/Explosion.s"
	@echo "... Source/SpaceInvaders/Entity/Invader.o"
	@echo "... Source/SpaceInvaders/Entity/Invader.i"
	@echo "... Source/SpaceInvaders/Entity/Invader.s"
	@echo "... Source/SpaceInvaders/Entity/Player.o"
	@echo "... Source/SpaceInvaders/Entity/Player.i"
	@echo "... Source/SpaceInvaders/Entity/Player.s"
	@echo "... Source/SpaceInvaders/Entity/Projectile.o"
	@echo "... Source/SpaceInvaders/Entity/Projectile.i"
	@echo "... Source/SpaceInvaders/Entity/Projectile.s"
	@echo "... Source/SpaceInvaders/Entity/Shield.o"
	@echo "... Source/SpaceInvaders/Entity/Shield.i"
	@echo "... Source/SpaceInvaders/Entity/Shield.s"
	@echo "... Source/SpaceInvaders/Entity/UFO.o"
	@echo "... Source/SpaceInvaders/Entity/UFO.i"
	@echo "... Source/SpaceInvaders/Entity/UFO.s"
	@echo "... Source/SpaceInvaders/InvaderManager.o"
	@echo "... Source/SpaceInvaders/InvaderManager.i"
	@echo "... Source/SpaceInvaders/InvaderManager.s"
	@echo "... Source/SpaceInvaders/StarryBackground.o"
	@echo "... Source/SpaceInvaders/StarryBackground.i"
	@echo "... Source/SpaceInvaders/StarryBackground.s"
	@echo "... Source/SpaceInvaders/States/StateHighscores.o"
	@echo "... Source/SpaceInvaders/States/StateHighscores.i"
	@echo "... Source/SpaceInvaders/States/StateHighscores.s"
	@echo "... Source/SpaceInvaders/States/StateMainMenu.o"
	@echo "... Source/SpaceInvaders/States/StateMainMenu.i"
	@echo "... Source/SpaceInvaders/States/StateMainMenu.s"
	@echo "... Source/SpaceInvaders/States/StatePlaying.o"
	@echo "... Source/SpaceInvaders/States/StatePlaying.i"
	@echo "... Source/SpaceInvaders/States/StatePlaying.s"
	@echo "... Source/SpaceInvaders/World.o"
	@echo "... Source/SpaceInvaders/World.i"
	@echo "... Source/SpaceInvaders/World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

